-- MySQL Script generated by MySQL Workbench
-- Sun Jul 26 19:22:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema surveydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema surveydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `surveydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `surveydb` ;

-- -----------------------------------------------------
-- Table `surveydb`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`answer` (
  `answer_id` BIGINT NOT NULL AUTO_INCREMENT,
  `answer_value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`answer_id`),
  UNIQUE INDEX `UK_eivoaw86mwbwvibfrhoxxbx75` (`answer_value` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `surveydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`question` (
  `question_id` BIGINT NOT NULL AUTO_INCREMENT,
  `multi_choice` BIT(1) NOT NULL,
  `question_value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`question_id`),
  UNIQUE INDEX `UK_reonjn97creggeccpu02lbg78` (`question_value` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `surveydb`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`survey` (
  `survey_id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(4000) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`survey_id`),
  UNIQUE INDEX `UK_gxdxj5pybp6ehgutebf8k9l3t` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `surveydb`.`user_survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`user_survey` (
  `user_survey_id` BIGINT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `survey_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_survey_id`),
  INDEX `FKackdbtqmhnel8sd1huwt57h3q` (`survey_id` ASC) VISIBLE,
  CONSTRAINT `FKackdbtqmhnel8sd1huwt57h3q`
    FOREIGN KEY (`survey_id`)
    REFERENCES `surveydb`.`survey` (`survey_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `surveydb`.`chosen_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`chosen_answer` (
  `chosen_answer_id` BIGINT NOT NULL AUTO_INCREMENT,
  `question_id` BIGINT NOT NULL,
  `user_survey_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`chosen_answer_id`),
  INDEX `FK2i38a54wyvyxnc81g041o7dmo` (`question_id` ASC) VISIBLE,
  INDEX `FKa0a2drcp1wrxc5yi24f1q20bc` (`user_survey_id` ASC) VISIBLE,
  CONSTRAINT `FK2i38a54wyvyxnc81g041o7dmo`
    FOREIGN KEY (`question_id`)
    REFERENCES `surveydb`.`question` (`question_id`),
  CONSTRAINT `FKa0a2drcp1wrxc5yi24f1q20bc`
    FOREIGN KEY (`user_survey_id`)
    REFERENCES `surveydb`.`user_survey` (`user_survey_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `surveydb`.`answers_chosen_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`answers_chosen_answers` (
  `chosen_answer_id` BIGINT NOT NULL,
  `answer_id` BIGINT NOT NULL,
  PRIMARY KEY (`chosen_answer_id`, `answer_id`),
  INDEX `FKpe2hii2vvpiir1m42xbyrppwg` (`answer_id` ASC) VISIBLE,
  CONSTRAINT `FK9yriu4oyx10egmy1ydyj8yers`
    FOREIGN KEY (`chosen_answer_id`)
    REFERENCES `surveydb`.`chosen_answer` (`chosen_answer_id`),
  CONSTRAINT `FKpe2hii2vvpiir1m42xbyrppwg`
    FOREIGN KEY (`answer_id`)
    REFERENCES `surveydb`.`answer` (`answer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `surveydb`.`questions_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`questions_answers` (
  `question_id` BIGINT NOT NULL,
  `answer_id` BIGINT NOT NULL,
  PRIMARY KEY (`question_id`, `answer_id`),
  INDEX `FK1512sjlud9f26538n18nmud4` (`answer_id` ASC) VISIBLE,
  CONSTRAINT `FK1512sjlud9f26538n18nmud4`
    FOREIGN KEY (`answer_id`)
    REFERENCES `surveydb`.`answer` (`answer_id`),
  CONSTRAINT `FK4wnm92xc0gdxq5m2oyokxsb8f`
    FOREIGN KEY (`question_id`)
    REFERENCES `surveydb`.`question` (`question_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `surveydb`.`survey_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `surveydb`.`survey_questions` (
  `survey_survey_id` BIGINT NOT NULL,
  `questions_question_id` BIGINT NOT NULL,
  PRIMARY KEY (`survey_survey_id`, `questions_question_id`),
  INDEX `FKcbgw5nk1a6xxwo6hi463iu4sb` (`questions_question_id` ASC) VISIBLE,
  CONSTRAINT `FKcbgw5nk1a6xxwo6hi463iu4sb`
    FOREIGN KEY (`questions_question_id`)
    REFERENCES `surveydb`.`question` (`question_id`),
  CONSTRAINT `FKsu5uj0v39bs01tgfv0i6718vl`
    FOREIGN KEY (`survey_survey_id`)
    REFERENCES `surveydb`.`survey` (`survey_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
